name: version-sync
description: This repository is for trying version migration

branding:
  icon: airplay
  color: yellow
    
configs:
  repo-metadata:
    parameters:
      description: 'A react-app template'
      topics:
        - react-app
        - nodejs
        - vercel
init:
  uses: stack-init.yaml
